Default PLA:
  type: PLA
  combinations:
    Default PLA:
      heatFactor: 3
      compressionFactor: 2
      reverse: false
    Default PETG:
      heatFactor: 0
      compressionFactor: 0
      reverse: false
    Default Soluble:
      heatFactor: 5
      compressionFactor: 3
      reverse: false
    Polysupport:
      heatFactor: 5
      compressionFactor: 2
      reverse: false
Default PETG:
  type: PETG
  combinations:
    Default PLA:
      heatFactor: 0
      compressionFactor: 0
      reverse: false
    Default PETG:
      heatFactor: 2
      compressionFactor: 2
      reverse: false
    Default Soluble:
      heatFactor: 0
      compressionFactor: 0
      reverse: false
    Polysupport:
      heatFactor: 0
      compressionFactor: 0
      reverse: false
Default Soluble:
  type: Soluble
  combinations:
    Default PLA:
      heatFactor: 5
      compressionFactor: 3
      reverse: false
    Default PETG:
      heatFactor: 0
      compressionFactor: 0
      reverse: false
    Default Soluble:
      heatFactor: 0
      compressionFactor: 0
      reverse: false
    Polysupport:
      heatFactor: 0
      compressionFactor: 0
      reverse: false
Polysupport:
  type: PLA
  combinations:
    Default PLA:
      heatFactor: 5
      compressionFactor: 2
      reverse: false
    Default PETG:
      heatFactor: 0
      compressionFactor: 0
      reverse: false
    Default Soluble:
      heatFactor: 6
      compressionFactor: 3
      reverse: false
    Polysupport:
      heatFactor: 5
      compressionFactor: 2
      reverse: false
